### ISSUE TITLE
Support for tokio-native-tls-comp?

### ISSUE THREAD

**Issue by EdmundsEcho** [jbr/async-redis-session#16]
Thank you for putting together this extension of the `async-redis` package.  

The redis dependency uses the  `features = ["aio", "async-std-comp"]`.  

Does that mean I can't use a client that uses tokio: `redis = { ... features = ["tokio-native-tls-comp"] }`?

**Comment by EdmundsEcho** [comment]
The question was based on a misunderstanding of how the crate features interact.   However, the motivation remains and thus an iteration on the question.

I needed to use `redis` with the following features:

```toml
[dependencies.redis]
version = "0.21.5"
features = ["aio", "async-std-comp", "async-std-tls-comp", "tls", "tokio-comp", "tokio-native-tls-comp"]
``` 

It would *not* compile with `async-redis-session`.  My versions of the overlapping types did not match.  The messages were a bit cryptic and led me to ask the first question.

In the end, I got the code to compile by changing `async-redis-session` dependencies to align with what I was using in redis.  This means I have my own version of the package (`path = ../async-redis-session`).

```toml
[dependencies.redis]
version = "0.21.5"     # << align with redis
features = ["aio", "async-std-comp"]
```

I did try to simply downgrade the version of redis to accomplish the alignment task.  I may have missed something, but I could not get it to work that way.

I would submit a PR with the updated dependency, but suspect that that might cause issues for others.  I'm not sufficiently versed in managing these dependency issues.

# Reworded question

What is the best way to align the version of `redis` with that of `async-redis-session`?  The snag is how to do so while enabling `ssl` (i.e., the feature set as described).

PS: The session works really well with redis.  It's truly amazing how simple it was to add this state functionality to the service.  Thank you!!
